### PR TITLE
Jessification

### PR DESCRIPTION
**Pull request by glasnt**
Hey @jfrazelle 

First off, THIS IS AWESOME! Thank you for running with it!

This PR makes a few changes: 
- theme: since you've chosen Jessie Island, I've picked a basic beach header/font to remove the KatieConf theme (specifically because the KatieConf header image is a Catherine wheel (da boom tish). I couldn't find any pictures of Jessie Island or Cowley Beach, so I've substituted with a CC-licenced pretty beach picture from another beach in Queensland
- Removed GA tracking
- Removed my name from the footer, referencing KatieConf itself. 

It also looks like you've missed your speaker images. 

Still, 🎉

### CODE REVIEW

**Comment by jessfraz** [comment]
Thanks!!!

**Comment by glasnt** [comment]
Whoop! 

Also, there's still copy at the bottom referencing organisers that you might want to remove.

**Comment by jessfraz** [comment]
ah good catch

On Tue, Jul 12, 2016 at 3:10 PM, Katie McLaughlin notifications@github.com
wrote:

> Whoop!
> 
> Also, there's still copy at the bottom referencing organisers that you
> might want to remove.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/jessconf/jessconf.github.io/pull/2#issuecomment-232182478,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABYNbPzBbepBEDs0v2mMwYlMVn3EXhfNks5qVALNgaJpZM4JK0Qy
> .

## 

Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3

**Comment by jessfraz** [comment]
omg this is a dope font!

**Pull request merged**
